# Generated by Django 4.0.5 on 2022-06-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=50)),
                ('horario_sucursal', models.CharField(max_length=50)),
                ('direccion_sucursal', models.CharField(max_length=50)),
                ('numero_telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Susursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
    ]
